M48
; DRILL file {KiCad (6.0.8-1)-1} date Wednesday, October 19, 2022 at 02:42:22 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-19T14:42:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X84.184Y-89.374
X107.184Y-107.224
T2
X71.62Y-71.69
X72.89Y-147.89
X118.6Y-147.9
X119.9Y-73.0
T0
M30
